### ISSUE TITLE
Notarization fails if there's a third-party .dylib in the .app

### ISSUE THREAD

**Issue by bfod** [EddieCameron/notarize-app#1]
You can force these things to be signed by running:

codesign --deep --force --verify --verbose --timestamp --options runtime --entitlements "<my entitlements>" --sign "<my developer id>" "MyGame.app/Contents/path-to-dylib"

Maybe you could just scan for these and run that automatically? Hi Eddie.

**Comment by EddieCameron** [comment]
I'm actually doing some work on this now. Was this for .dylibs placed somewhere the Unity Assets folder, as plugins? Hi Bennett.

**Comment by bfod** [comment]
Yes, third party plugins as .dylibs in the asset folder. For now I just manually codesign all of the dylibs in the .app package. Also hi Eddie I hope you folks are doing ok in New Zealand.

**Comment by EddieCameron** [comment]
Do you re-do the ones in `/Frameworks` as well? They already get/are signed but if it doesn't care about "double-signing" I'll just sign all the *.dylibs I can find. We are doing fine and I hope you and yours are as well.

**Comment by bfod** [comment]
Yeah the frameworks dylibs also came back failed in Apple’s weird notarization log, so I also have been signing those manually.

**Comment by EddieCameron** [comment]
New version should hopefully do this all for you now

**Comment by bfod** [comment]
You are a hero
